
-- HABILITAR UUID
create extension if not exists "uuid-ossp";

-- 1. TABLA USERS
create table public.users (
  id text primary key, -- Usamos text para permitir IDs manuales como '12345678'
  nombre text not null,
  role text not null,
  email text,
  edad int,
  condicion text,
  meta_pasos_diaria int default 3000,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. TABLA VIDEOS
create table public.videos (
  id text primary key,
  numero_orden int,
  titulo text,
  descripcion text,
  youtube_video_id text,
  tipo_ejercicio text,
  grupos_musculares text[],
  repeticiones_sugeridas text,
  equipamiento_necesario text[],
  nivel_dificultad text,
  duracion_estimada_minutos int
);

-- 3. TABLA WALK SESSIONS
create table public.walk_sessions (
  id bigint generated by default as identity primary key,
  patient_id text references public.users(id),
  date text,
  duration_seconds int,
  steps int,
  pain_level int,
  stopped_due_to_pain boolean,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. TABLA EXERCISE LOGS
create table public.exercise_logs (
  id bigint generated by default as identity primary key,
  patient_id text references public.users(id),
  video_id text references public.videos(id),
  fecha_realizacion text,
  timestamp text,
  series_completadas int,
  repeticiones_completadas int,
  dificultad_percibida int,
  dolor_durante_ejercicio int,
  completado boolean
);

-- 5. TABLA ASSIGNMENTS (Configuración de Rutina)
create table public.assignments (
  patient_id text primary key references public.users(id),
  video_ids text[], -- Array de IDs de videos
  config jsonb, -- { series, reps, notes }
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 6. TABLA CLINICAL METRICS
create table public.clinical_metrics (
  patient_id text primary key references public.users(id),
  fecha_evaluacion text,
  peso_kg numeric,
  imc numeric,
  fc_reposo int,
  fc_max_teorica int,
  fc_reserva int,
  itb_derecho numeric,
  itb_izquierdo numeric,
  test_marcha_6min_metros int,
  sts_30_seg_reps int,
  cuestionario_eq5d_puntaje int
);

-- DATOS INICIALES (SEED)

-- Usuarios
INSERT INTO public.users (id, nombre, role, email, edad, condicion, meta_pasos_diaria) VALUES
('12345678', 'Paciente Pruebas', 'paciente', null, 75, 'EAP Moderada', 4500),
('d1', 'Dr. Silva', 'medico', 'medico@test.com', 40, null, null);

-- Videos (Los mismos del prototipo)
INSERT INTO public.videos (id, numero_orden, titulo, descripcion, youtube_video_id, tipo_ejercicio, grupos_musculares, repeticiones_sugeridas, equipamiento_necesario, nivel_dificultad, duracion_estimada_minutos) VALUES
('v1', 1, 'Variante Pararse y Sentarse', 'Ejercicio fundamental para fortalecer piernas.', 'O7oFiCMN25E', 'fuerza_eeii', ARRAY['cuadriceps'], '2-3 series • 8-15 reps', ARRAY['silla'], 'principiante', 5),
('v2', 2, 'Remo con Banda Elástica', 'Fortalecimiento de espalda.', 'J3VFboUbubo', 'resistencia', ARRAY['dorsal'], '2-3 series • 10-15 reps', ARRAY['banda_elastica'], 'intermedio', 6),
('v3', 3, 'Pararse y Sentarse', 'Funcional clásico.', 'gWdgSzPrncU', 'fuerza_eeii', ARRAY['cuadriceps'], '2-3 series • 8-12 reps', ARRAY['silla'], 'principiante', 5),
('v4', 4, 'Extensión de Glúteo (V1)', 'Cadera posterior.', 'G00dG-33QqA', 'fuerza_eeii', ARRAY['gluteos'], '2-3 series • 10-15 reps', ARRAY['banda'], 'intermedio', 4),
('v5', 5, 'Extensión de Glúteo (V2)', 'Control muscular.', 'pX7DEPwYXEE', 'fuerza_eeii', ARRAY['gluteos'], '2-3 series • 10-15 reps', ARRAY['banda'], 'principiante', 4),
('v6', 6, 'Extensión de Cuádriceps', 'Muslos con peso.', 'zEa1Eq3yIsw', 'fuerza_eeii', ARRAY['cuadriceps'], '2-3 series • 10-15 reps', ARRAY['tobilleras'], 'intermedio', 5),
('v7', 7, 'Elevación de Talones', 'Retorno venoso.', '0caP82ZUo1I', 'fuerza_eeii', ARRAY['pantorrillas'], '2-3 series • 15-20 reps', ARRAY['silla'], 'principiante', 3),
('v8', 8, 'Curl Bíceps', 'Brazos actividades diarias.', '-FNnffnCPxE', 'resistencia', ARRAY['biceps'], '2-3 series • 10-15 reps', ARRAY['mancuernas'], 'principiante', 4);

-- HABILITAR ACCESO PUBLICO (Importante para prototipo sin auth compleja)
alter table public.users enable row level security;
create policy "Public Access" on public.users for select using (true);
create policy "Public Insert" on public.users for insert with check (true);
create policy "Public Update" on public.users for update using (true);

alter table public.videos enable row level security;
create policy "Public Access" on public.videos for all using (true);

alter table public.walk_sessions enable row level security;
create policy "Public Access" on public.walk_sessions for all using (true);

alter table public.exercise_logs enable row level security;
create policy "Public Access" on public.exercise_logs for all using (true);

alter table public.assignments enable row level security;
create policy "Public Access" on public.assignments for all using (true);

alter table public.clinical_metrics enable row level security;
create policy "Public Access" on public.clinical_metrics for all using (true);
